import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { api, command, disconnect, initialize, reconnect, requestId, store, useSession } from './client';
import { audioEngine, useAudio } from './audio/engine';
import { languagesSchema, settingsSchema, statusText, type Caption, type Language, type Settings, type Snapshot } from './model';

function Icon({ name }: { name: 'wave' | 'arrow' | 'play' | 'mic' | 'headphones' | 'check' | 'settings' | 'sun' }) {
  const paths = { wave: 'M3 10v4m4-8v12m5-16v20m5-16v12m4-8v4', arrow: 'M4 12h16m-6-6 6 6-6 6', play: 'm8 5 11 7-11 7Z', mic: 'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0Zm-3 6v1a6 6 0 0 0 12 0v-1M12 18v4m-4 0h8', headphones: 'M3 14v-3a9 9 0 0 1 18 0v3M3 12h4v9H3Zm14 0h4v9h-4Z', check: 'm5 12 4 4L19 6', settings: 'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8m0-6v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2', sun: 'M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2' };
  return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]} /></svg>;
}
function Badge({ status, children }: { status: string; children?: ReactNode }) { return <span className={`badge ${['active', 'streaming', 'connected', 'ready', 'running', 'playing'].includes(status) ? 'good' : ['error', 'denied', 'auth_required', 'degraded'].includes(status) ? 'bad' : ''}`}><span className="dot" />{children || statusText(status)}</span>; }
function Notice({ children, error = false }: { children: ReactNode; error?: boolean }) { return <div className={`notice ${error ? 'error' : ''}`} role={error ? 'alert' : 'status'}>{children}</div>; }
function useAction() {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function run(action: () => Promise<unknown>, success = '') { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await action(); setNotice(success); } catch (err) { setError(err instanceof Error ? err.message : '操作を完了できませんでした。'); } finally { setBusy(false); } }
  return { busy, error, notice, run, feedback: <>{error && <Notice error>{error}</Notice>}{notice && <Notice>{notice}</Notice>}</> };
}
function LanguageSelect({ label, value, onChange, languages, disabled = false }: { label: string; value: string; onChange: (value: string) => void; languages: Language[]; disabled?: boolean }) {
  return <label className="field"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)} disabled={disabled}>{languages.map(language => <option key={language.code} value={language.code}>{language.name_ja}</option>)}</select></label>;
}
function useLanguages() {
  const { bootstrap } = useSession(); const [languages, setLanguages] = useState<Language[]>(bootstrap?.languages || []);
  useEffect(() => { if (bootstrap?.languages) setLanguages(bootstrap.languages); else if (bootstrap?.surface === 'participant') void api<{ languages: unknown }>('/api/v1/languages').then(data => setLanguages(languagesSchema.parse(data.languages))).catch(() => undefined); }, [bootstrap]);
  return languages.length ? languages : [{ code: 'zh', name_ja: '中国語' }, { code: 'ja', name_ja: '日本語' }, { code: 'en', name_ja: '英語' }];
}
function languageName(languages: Language[], code: string) { return languages.find(language => language.code === code)?.name_ja || code; }

export function App() {
  const state = useSession(); const [theme, setTheme] = useState('system');
  useEffect(() => { void initialize(); }, []);
  useEffect(() => { setTheme(state.bootstrap?.settings?.theme || 'system'); }, [state.bootstrap?.settings?.theme]);
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  const participant = state.bootstrap?.surface === 'participant';
  return <div className="app-shell">
    <a className="skip-link" href="#main">本文へ移動</a>
    <header className="header"><Link className="brand" to={participant ? '/b' : '/'}><span className="brand-icon"><Icon name="wave" /></span>Translator<span className="brand-note">言葉でつながる</span></Link><nav aria-label="メインナビゲーション">{!participant && <><NavLink to="/" end>ホーム</NavLink><NavLink to="/settings">設定</NavLink><NavLink to="/diagnostics">診断</NavLink></>}<button className="icon-button" title="テーマを切り替え" aria-label="テーマを切り替え" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}><Icon name="sun" /></button></nav></header>
    <main id="main" className="main">
      {!state.ready ? <div className="empty loading"><span className="spinner" /><h1>Translator を準備しています</h1><p>音声はまだ送信されていません。</p></div> : !state.bootstrap ? <div className="empty"><h1>アプリとの接続を確認してください</h1><Notice error>{state.error}</Notice><button onClick={reconnect}>再接続する</button></div> : <>
        {(state.snapshot?.demo || (!state.snapshot && state.bootstrap.demo)) && <div className="demo-banner"><span className="demo-tag">DEMO</span>デモ：実際の音声認識・翻訳ではありません。マイク・外部 API は使用しません。</div>}
        {state.connection === 'reconnecting' && <Notice>接続が切れました。自動で再接続しています。復帰後に現在の状態を取得します。<button className="text-button" onClick={reconnect}>今すぐ再接続</button></Notice>}
        {state.error && <Notice error>{state.error}</Notice>}
        <Routes>
          <Route path="/" element={participant ? <Navigate to="/b" replace /> : <HomePage />} />
          <Route path="/setup" element={participant ? <Navigate to="/b" replace /> : <SettingsPage wizard />} />
          <Route path="/settings" element={participant ? <Navigate to="/b" replace /> : <SettingsPage />} />
          <Route path="/diagnostics" element={participant ? <Navigate to="/b" replace /> : <DiagnosticsPage />} />
          <Route path="/a" element={participant ? <Navigate to="/b" replace /> : <PrompterPage />} />
          <Route path="/join" element={<SpeakerPage />} /><Route path="/b" element={<SpeakerPage />} />
          <Route path="*" element={<div className="empty"><h1>ページが見つかりません</h1><Link to="/">ホームへ</Link></div>} />
        </Routes>
      </>}
    </main>
    <footer><span>Translator <span className="footer-dot">·</span> 声を、わかる言葉に。</span><span>音声と会話本文は既定で保存されません</span></footer>
  </div>;
}

function HomePage() {
  const { bootstrap, snapshot, connection } = useSession(); const settings = bootstrap?.settings; const languages = useLanguages(); const navigate = useNavigate(); const action = useAction();
  const [source, setSource] = useState(settings?.source_language || 'zh'); const [target, setTarget] = useState(settings?.target_language || 'ja'); const [translation, setTranslation] = useState(settings?.translation_enabled ?? true);
  const active = snapshot && !['ended', 'idle'].includes(snapshot.status);
  async function start(demo: boolean) {
    if (active) { navigate('/a'); return; }
    const created = snapshot?.status === 'idle' ? snapshot : await api<Snapshot>('/api/local/sessions', 'POST', { request_id: requestId(), source_language: source, target_language: target, translation_enabled: translation, demo }); store.snapshot(created);
    store.snapshot(await api(`/api/local/sessions/${created.session_id}/start`, 'POST', { request_id: requestId() })); navigate('/a');
  }
  const configured = Boolean(settings?.secrets.gladia?.configured && (!translation || source === target || settings?.secrets.deepl?.configured));
  return <>
    <div className="eyebrow"><span className="small-line" /> YOUR CONVERSATION, CONNECTED</div>
    <section className="home-heading"><div><h1>言葉の先へ、<br /><em>会話をつなぐ。</em></h1><p>相手の言葉を、読みやすい字幕に。<br />PC の音声も、そのまま相手に届けられます。</p></div><div className="conversation-art" aria-hidden="true"><div className="art-card original"><span>你好，很高兴认识你。</span><small>中国語</small></div><div className="art-flow"><i /><i /><i /><i /><i /><i /><i /><Icon name="arrow" /></div><div className="art-card translated"><span>はじめまして。<br />お会いできてうれしいです。</span><small>日本語</small><span className="art-spark">✦</span></div><span className="art-caption">声が届く。言葉が伝わる。</span></div></section>
    <div className="home-grid"><section className="panel session-panel"><div className="section-heading"><div><span className="eyebrow">START A CONVERSATION</span><h2>通訳をはじめる</h2></div><Badge status={active ? snapshot.status : 'idle'}>{active ? statusText(snapshot.status) : '音声送信なし'}</Badge></div>
      <div className="language-pair"><LanguageSelect label="相手が話す言語" value={source} onChange={setSource} languages={languages} disabled={Boolean(active)} /><div className="direction-arrow"><Icon name="arrow" /></div><LanguageSelect label="字幕を表示する言語" value={target} onChange={setTarget} languages={languages} disabled={Boolean(active)} /></div>
      <label className="switch-row"><div><strong>字幕を翻訳する</strong><small>{source === target ? '同じ言語では原文を表示します' : '相手の発言を、選択した言語で表示します'}</small></div><input type="checkbox" className="switch" checked={translation} onChange={event => setTranslation(event.target.checked)} disabled={Boolean(active)} /></label>
      <div className="privacy-line"><Icon name="headphones" /><span>PC 音声の共有は、開始後に選択できます。</span></div>
      <button className="primary wide" disabled={action.busy || connection !== 'connected' || (!active && !configured && !bootstrap?.demo)} onClick={() => void action.run(() => start(Boolean(bootstrap?.demo)))}><Icon name="play" />{action.busy ? '準備しています…' : active ? '会話の画面に戻る' : bootstrap?.demo ? 'デモを開始' : '通訳を開始'}<Icon name="arrow" /></button>
      {!configured && !active && !bootstrap?.demo && <p className="form-hint">実際の通訳にはサービスの設定が必要です。<Link to="/setup">初回設定へ</Link></p>}{action.feedback}
      <div className="readiness"><span>音声認識 <b>{settings?.secrets.gladia?.configured ? '設定済み・未検証' : '未設定'}</b></span><span>翻訳 <b>{settings?.secrets.deepl?.configured ? '設定済み・未検証' : '未設定'}</b></span></div>
    </section><aside className="home-aside"><section className="demo-card"><span className="pill">はじめての方へ</span><h2>まずは、体験してみる。</h2><p>API キーもマイクも不要。<br />字幕が届く流れをローカルデモで確認できます。</p><button className="secondary wide" disabled={action.busy || Boolean(active) || connection !== 'connected'} onClick={() => void action.run(() => start(true))}>デモを試す <Icon name="arrow" /></button></section><section className="how-card"><span className="eyebrow">HOW IT WORKS</span><ol><li><span>01</span><div><strong>この PC で通訳を開始</strong><small>あなたは字幕を見る人（A）です</small></div></li><li><span>02</span><div><strong>相手に招待リンクを共有</strong><small>相手はブラウザだけで参加できます</small></div></li><li><span>03</span><div><strong>相手がマイクを開始</strong><small>発言が原文と翻訳の字幕になります</small></div></li></ol></section></aside></div>
  </>;
}

export function CaptionView({ caption, showOriginal = true }: { caption: Caption; showOriginal?: boolean }) {
  const t = caption.translation; const originalPrimary = ['disabled', 'same_language'].includes(t.status);
  return <article className="caption" data-utterance-id={caption.utterance_id}>
    <div className="caption-meta"><span>{caption.original.is_final ? '確定' : '認識中'}</span><span>{caption.source_language} → {caption.target_language}</span></div>
    {showOriginal && !originalPrimary && <p className="original-text" lang={caption.source_language}>{caption.original.text}</p>}
    {originalPrimary ? <><small>原文表示</small><p className="translated-text" lang={caption.source_language}>{caption.original.text}</p></> : t.status === 'ready' ? <p className="translated-text" lang={caption.target_language}>{t.text}</p> : <><p className="translation-status">{t.status === 'error' ? '翻訳できませんでした。原文を確認してください。' : '翻訳中…'}</p>{!showOriginal && <p lang={caption.source_language}>{caption.original.text}</p>}</>}
  </article>;
}
function CaptionFeed({ snapshot, showOriginal, fontSize, announce }: { snapshot: Snapshot; showOriginal: boolean; fontSize: number; announce: boolean }) {
  const captions = Object.values(snapshot.captions).slice(-20); const latest = captions.at(-1); const history = captions.slice(0, -1); const scroll = useRef<HTMLDivElement>(null); const [follow, setFollow] = useState(true);
  useEffect(() => { if (follow && scroll.current) scroll.current.scrollTop = scroll.current.scrollHeight; }, [snapshot.captions, follow]);
  return <section className="caption-panel panel" style={{ '--caption-size': `${fontSize}px` } as CSSProperties}>
    <div className="caption-panel-heading"><span className="eyebrow">LIVE CAPTIONS</span><Badge status={snapshot.status} /></div>
    <div ref={scroll} className="caption-scroll" onScroll={() => { const el = scroll.current!; setFollow(el.scrollHeight - el.scrollTop - el.clientHeight < 70); }}>
      {history.length > 0 && <details className="caption-history"><summary>過去の発言（{history.length} 件）</summary>{history.map(caption => <CaptionView key={caption.utterance_id} caption={caption} showOriginal={showOriginal} />)}</details>}
      {latest ? <CaptionView caption={latest} showOriginal={showOriginal} /> : <div className="caption-empty"><span className="empty-wave"><Icon name="wave" /></span><h2>相手の言葉が、ここに届きます。</h2><p>{snapshot.demo ? 'ローカルのデモ音声を処理しています。' : '招待リンクから参加し、相手がマイクを開始すると字幕が表示されます。'}</p></div>}
    </div>
    {!follow && <button className="follow-button" onClick={() => setFollow(true)}>最新に戻る ↓</button>}
    <div className="sr-only" aria-live={announce ? 'polite' : 'off'} aria-atomic="true">{latest?.original.is_final ? latest.translation.status === 'ready' && latest.translation.is_final ? latest.translation.text : latest.original.text : ''}</div>
    <div className="caption-bottom"><span className="dot" />{snapshot.status === 'ended' ? 'この会話は終了しました' : '字幕は自動で更新されます'}<span>表示 20 件 / 保持 100 発言まで</span></div>
  </section>;
}
function PathStatus({ snapshot }: { snapshot: Snapshot }) { const { connection } = useSession(); return <div className="path-status"><span>画面 <Badge status={connection} /></span>{[['mic_status', '相手のマイク'], ['stt_status', '音声認識'], ['translation_status', '翻訳']].map(([key, name]) => <span key={key}>{name} <Badge status={snapshot.components[key] || 'idle'} /></span>)}</div>; }

function PrompterPage() {
  const { snapshot, bootstrap, connection } = useSession(); const languages = useLanguages(); const action = useAction(); const navigate = useNavigate(); const [showOriginal, setShowOriginal] = useState(bootstrap?.settings?.show_original ?? true); const [fontSize, setFontSize] = useState(bootstrap?.settings?.caption_font_size || 32); const [announce, setAnnounce] = useState(false); const [invite, setInvite] = useState(''); const [devices, setDevices] = useState<{ id: string; name: string }[]>([]); const [deviceId, setDeviceId] = useState(bootstrap?.settings?.loopback_device_id || ''); const inviteDialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { void api('/api/local/audio/devices').then(value => { const data = z.object({ devices: z.array(z.object({ id: z.string(), name: z.string() }).passthrough()) }).safeParse(value); if (data.success) setDevices(data.data.devices); }).catch(() => undefined); }, []);
  useEffect(() => { if (invite) inviteDialog.current?.showModal(); }, [invite]);
  if (!snapshot) return <div className="empty"><h1>まだ会話を開始していません</h1><Link className="button primary" to="/">ホームで通訳を開始</Link></div>;
  const stopped = ['ended', 'stopping'].includes(snapshot.status); const sharing = ['active', 'streaming'].includes(snapshot.components.system_audio_status);
  return <><div className="page-heading"><div><span className="eyebrow">LISTENER · A</span><h1>会話に、耳を傾ける。</h1><p>{languageName(languages, snapshot.source_language)} <span className="direction-text">→</span> {languageName(languages, snapshot.target_language)}</p></div><button disabled={action.busy || stopped || snapshot.demo} onClick={() => void action.run(async () => { const result = await api<{ url: string }>(`/api/local/sessions/${snapshot.session_id}/invites`, 'POST', { request_id: requestId(), role: 'speaker' }); setInvite(result.url); })}>招待リンクを作成 <Icon name="arrow" /></button></div>
    <PathStatus snapshot={snapshot} />{action.feedback}
    <div className="prompter-layout"><CaptionFeed snapshot={snapshot} showOriginal={showOriginal} fontSize={fontSize} announce={announce} /><aside className="conversation-controls">
      <details className="panel controls-details" open><summary>字幕の設定</summary><div className="controls-content"><LanguageSelect label="字幕の言語" languages={languages} value={snapshot.target_language} onChange={language => void action.run(() => command('set_target_language', { language }))} disabled={action.busy || stopped || connection !== 'connected'} /><label className="switch-row"><span>翻訳する</span><input className="switch" type="checkbox" checked={snapshot.translation_enabled} disabled={action.busy || stopped} onChange={event => void action.run(() => command('set_translation_enabled', { enabled: event.target.checked }))} /></label><label className="check-row"><input type="checkbox" checked={showOriginal} onChange={event => setShowOriginal(event.target.checked)} />原文も表示</label><label className="field"><span>文字サイズ <b>{fontSize} px</b></span><input type="range" min="24" max="64" step="2" value={fontSize} onChange={event => setFontSize(Number(event.target.value))} /></label><label className="check-row"><input type="checkbox" checked={announce} onChange={event => setAnnounce(event.target.checked)} />確定字幕を読み上げ通知</label><button className="secondary wide" onClick={() => void action.run(async () => { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen(); })}>全画面表示</button></div></details>
      <section className="panel audio-share"><div className="section-heading"><h2>PC の音声共有</h2><Badge status={snapshot.components.system_audio_status || 'idle'} /></div><p>選択した出力の音声が相手に届きます。通知音や他のアプリの音も含まれます。</p><label className="field"><span>音声を取得する出力</span><select value={deviceId} onChange={event => setDeviceId(event.target.value)} disabled={sharing}><option value="">既定の出力</option>{devices.map(device => <option key={device.id} value={device.id}>{device.name}</option>)}</select></label><button className={sharing ? 'danger wide' : 'secondary wide'} disabled={action.busy || stopped || snapshot.demo} onClick={() => void action.run(async () => store.snapshot(await api(`/api/local/sessions/${snapshot.session_id}/system-audio`, 'POST', { request_id: requestId(), enabled: !sharing, device_id: deviceId || undefined })))}><Icon name="headphones" />{sharing ? '音声共有を停止' : '音声共有を開始'}</button></section>
      <button className="danger wide" disabled={action.busy || stopped} onClick={() => void action.run(async () => { store.snapshot(await api(`/api/local/sessions/${snapshot.session_id}/stop`, 'POST', { request_id: requestId() })); navigate('/'); })}>通訳を終了</button>
    </aside></div>
    <dialog ref={inviteDialog}><div className="dialog-heading"><h2>相手を会話に招待</h2><button className="text-button" onClick={() => inviteDialog.current?.close()}>閉じる</button></div><p>相手がこのリンクを開き、マイクを開始すると参加できます。有効期限は 10 分です。</p><label className="field"><span>招待リンク</span><input readOnly value={invite} onFocus={event => event.target.select()} /></label><button className="primary wide" onClick={() => void action.run(async () => { await navigator.clipboard.writeText(invite); }, '招待リンクをコピーしました。')}>招待リンクをコピー</button><p className="form-hint">別の PC からは HTTPS の公開リンクが必要です。<Link to="/settings" onClick={() => inviteDialog.current?.close()}>リモート接続を設定</Link></p>{action.feedback}</dialog>
  </>;
}

function SpeakerPage() {
  const { snapshot, bootstrap } = useSession(); const audio = useAudio(); const languages = useLanguages(); const action = useAction(); const [deviceId, setDeviceId] = useState(''); const [devices, setDevices] = useState<MediaDeviceInfo[]>([]); const [volume, setVolume] = useState(80); const [left, setLeft] = useState(false);
  useEffect(() => { const update = () => { void navigator.mediaDevices?.enumerateDevices().then(setDevices).catch(() => undefined); }; update(); navigator.mediaDevices?.addEventListener('devicechange', update); return () => { navigator.mediaDevices?.removeEventListener('devicechange', update); void audioEngine.stop(); }; }, []);
  useEffect(() => { if (audio.mic === 'streaming') void navigator.mediaDevices?.enumerateDevices().then(setDevices); }, [audio.mic]);
  useEffect(() => { if (snapshot && ['ended', 'stopping'].includes(snapshot.status)) void audioEngine.stop(); }, [snapshot?.status]);
  if (bootstrap?.surface !== 'participant') return <div className="empty"><h1>話す人の画面は招待リンクから開きます</h1><Link to="/a">字幕画面で招待リンクを作成</Link></div>;
  if (!snapshot || left || !bootstrap.authenticated) return <div className="empty"><span className="empty-wave"><Icon name="mic" /></span><h1>{left ? '会話から退出しました' : '招待リンクで参加してください'}</h1><p>字幕を見る人（A）から届いた招待リンクを開いてください。<br />マイクは開始されていません。</p></div>;
  const streaming = ['streaming', 'muted'].includes(audio.mic); const stopped = ['ended', 'stopping'].includes(snapshot.status);
  return <><div className="page-heading"><div><span className="eyebrow">SPEAKER · B</span><h1>あなたの言葉を、届けよう。</h1><p>音声を文字起こしし、相手の画面に翻訳して表示します。</p></div><Badge status={snapshot.status} /></div>
    <div className="speaker-layout"><section className="panel microphone-panel"><div className="mic-symbol"><Icon name="mic" /></div><h2>{audio.mic === 'streaming' ? 'あなたの声を届けています' : audio.mic === 'muted' ? 'マイクを一時ミュート中' : ['requesting_permission', 'ready'].includes(audio.mic) ? 'マイクを準備しています' : '話す準備をしましょう'}</h2><p>{audio.mic === 'streaming' ? 'マイクの音声を送信しています。停止ボタンでいつでも終了できます。' : audio.mic === 'muted' ? '現在は無音を送信しています。解除すると音声送信が再開します。' : audio.mic === 'requesting_permission' ? 'ブラウザでマイクの使用を許可してください。' : audio.mic === 'ready' ? '音声認識サービスの準備ができるまでお待ちください。' : '開始ボタンを押すと、マイクの許可を確認します。'}<br />音声は音声認識サービス、認識文は翻訳サービスへ送られます。</p>
      <LanguageSelect label="あなたが話す言語" value={snapshot.source_language} languages={languages} onChange={language => void action.run(() => command('set_source_language', { language }))} disabled={streaming || action.busy || stopped} />
      <label className="field"><span>マイク</span><select value={deviceId} onChange={event => setDeviceId(event.target.value)} disabled={streaming || audio.mic === 'requesting_permission'}><option value="">既定のマイク</option>{devices.filter(device => device.kind === 'audioinput' && device.deviceId !== 'default').map((device, i) => <option key={device.deviceId || i} value={device.deviceId}>{device.label || `マイク ${i + 1}`}</option>)}</select></label>
      <div className="meter-heading"><span>入力レベル</span><Badge status={audio.mic} /></div><meter min="0" max="1" value={Math.min(1, audio.level * 4)} aria-label="マイク入力レベル" />
      {streaming ? <div className="button-row"><button className="secondary" onClick={() => audioEngine.mute()}>{audio.mic === 'muted' ? 'ミュートを解除' : '一時ミュート'}</button><button className="danger" onClick={() => void audioEngine.stopMic()}>マイクを停止</button></div> : <button className="primary wide" disabled={stopped || ['requesting_permission', 'ready'].includes(audio.mic) || action.busy} onClick={() => void audioEngine.start(snapshot, deviceId)}><Icon name="mic" />{audio.mic === 'requesting_permission' ? 'マイクの許可を確認中…' : audio.mic === 'ready' ? '音声認識を準備中…' : '参加してマイクを開始'}</button>}
      {audio.mic === 'requesting_permission' && <button className="text-button" onClick={() => void audioEngine.stopMic()}>キャンセル</button>}
      <p className="form-hint">一時ミュートは無音を送信します。30 秒後に認識を停止します。</p>{audio.error && <Notice error>{audio.error}</Notice>}{action.feedback}
      <div className="playback-controls"><div className="section-heading"><h2><Icon name="headphones" /> 相手からの音声</h2><Badge status={audio.playback} /></div><label className="field"><span>音量 <b>{volume}%</b></span><input type="range" min="0" max="100" value={volume} onChange={event => { setVolume(Number(event.target.value)); audioEngine.setVolume(Number(event.target.value) / 100); }} /></label><div className="button-row"><button onClick={() => void action.run(() => audioEngine.testTone())}>テスト音</button><button disabled={stopped} onClick={() => void action.run(() => audioEngine.startPlayback(snapshot))}>音声受信を開始</button></div><p className="form-hint">出力先は OS の音声設定から変更できます。</p>{audio.queueMs > 160 && <Notice>回線が混雑しています。古い未再生音声を破棄して復旧します。</Notice>}</div>
    </section><div><CaptionFeed snapshot={snapshot} showOriginal fontSize={28} announce={false} /><PathStatus snapshot={snapshot} /><button className="text-button leave-button" onClick={() => void action.run(async () => { await audioEngine.stop(); await api('/api/v1/leave', 'POST', { request_id: requestId() }); disconnect(); setLeft(true); })}>会話から退出する</button></div></div>
  </>;
}

export function SecretField({ provider, label, configured }: { provider: string; label: string; configured: boolean }) {
  const [key, setKey] = useState(''); const [persist, setPersist] = useState(true); const [saved, setSaved] = useState(configured); const action = useAction();
  return <div className="secret-field"><div className="section-heading"><h3>{label}</h3><Badge status="idle">{saved ? '設定済み' : '未設定'}</Badge></div><form onSubmit={event => { event.preventDefault(); const value = key; setKey(''); void action.run(async () => { const result = settingsSchema.parse(await api(`/api/local/secrets/${provider}`, 'PUT', { key: value, persist })); const current = store.get().bootstrap; if (current) store.update({ bootstrap: { ...current, settings: result } }); setSaved(true); }, 'キーを設定しました。接続確認は下のボタンで実行できます。'); }}><label className="field"><span>API キー{provider === 'ngrok' ? ' / 認証トークン' : ''}</span><input type="password" autoComplete="new-password" spellCheck={false} value={key} onChange={event => setKey(event.target.value)} placeholder={saved ? '変更する場合だけ入力' : 'キーを入力'} required maxLength={4096} aria-describedby={`${provider}-hint`} /></label><p id={`${provider}-hint`} className="form-hint">キーはブラウザに保存しません。送信後、入力欄を消去します。</p><label className="check-row"><input type="checkbox" checked={persist} onChange={event => setPersist(event.target.checked)} />OS の資格情報ストアに保存する</label><div className="button-row"><button type="submit" disabled={!key.trim() || action.busy}>キーを設定</button>{provider !== 'ngrok' && <button type="button" disabled={!saved || action.busy} onClick={() => void action.run(async () => { const result = await api<{ ok?: boolean; message?: string }>(`/api/local/providers/${provider}/test`, 'POST', { request_id: requestId() }); if (result.ok === false) throw new Error(result.message || 'サービスの接続確認に失敗しました。'); }, 'サービスから接続確認の応答を受け取りました。')}>接続を確認</button>}</div></form>{provider !== 'ngrok' && <p className="form-hint">接続確認はキーをサービスに送信します。API 利用が発生する場合があります。</p>}{action.feedback}</div>;
}
function SettingsPage({ wizard = false }: { wizard?: boolean }) {
  const { bootstrap } = useSession(); const [settings, setSettings] = useState<Settings | null>(bootstrap?.settings || null); const action = useAction(); const languages = useLanguages(); const [step, setStep] = useState(0); const [publicUrl, setPublicUrl] = useState(''); const [finished, setFinished] = useState(false);
  useEffect(() => { void api('/api/local/settings').then(value => setSettings(settingsSchema.parse(value))).catch(() => undefined); }, []);
  if (!settings) return <div className="empty"><h1>設定を読み込めませんでした</h1><button onClick={reconnect}>再接続</button></div>;
  function update<K extends keyof Settings>(name: K, value: Settings[K]) { setSettings(old => old ? { ...old, [name]: value } : old); }
  async function save() {
    if (!settings) return;
    const { revision, secrets: _secrets, ...values } = settings;
    const saved = settingsSchema.parse(await api('/api/local/settings', 'PATCH', { request_id: requestId(), expected_revision: revision, settings: { source_language: values.source_language, target_language: values.target_language, translation_enabled: values.translation_enabled, deepl_mode: values.deepl_mode, loopback_device_id: values.loopback_device_id, remote_domain: values.remote_domain || null, theme: values.theme, caption_font_size: values.caption_font_size, show_original: values.show_original } })); setSettings(saved);
    const current = store.get().bootstrap; if (current) store.update({ bootstrap: { ...current, settings: saved } });
  }
  return <><div className="page-heading"><div><span className="eyebrow">{wizard ? 'GET STARTED' : 'PREFERENCES'}</span><h1>{wizard ? 'あなたの会話に、合わせる。' : '設定'}</h1><p>保存した設定は次回も使えます。音声は自動で開始しません。</p></div><Link className="button" to="/">ホームへ戻る</Link></div>
    {bootstrap?.env_available && <Notice>既存の .env 設定が見つかりました。<button className="text-button" disabled={action.busy} onClick={() => void action.run(async () => { const imported = settingsSchema.parse(await api('/api/local/settings/import-env', 'POST', { request_id: requestId(), persist: false })); setSettings(imported); const current = store.get().bootstrap; if (current) store.update({ bootstrap: { ...current, settings: imported } }); }, '既存設定を今回の起動に取り込みました。元の .env は保持しています。')}>既存設定を今回のみ取り込む</button></Notice>}
    {wizard && <ol className="steps">{['使い方', 'サービス', '音声と接続', '完了'].map((label, i) => <li key={label} className={step === i ? 'current' : ''}><span>{i + 1}</span>{label}</li>)}</ol>}
    {wizard && step === 0 ? <div className="setup-choices"><section className="panel"><span className="pill">キー・マイク不要</span><h2>まずはデモを試す</h2><p>ローカルで動くサンプル字幕で、操作の流れを確認します。</p><Link className="button primary" to="/">ホームでデモを開始 <Icon name="arrow" /></Link></section><section className="panel"><span className="pill">実際の会話に</span><h2>通訳の準備をする</h2><p>この PC で通訳をホストし、相手は招待リンクから参加します。</p><button className="primary" onClick={() => setStep(1)}>サービスを設定 <Icon name="arrow" /></button></section></div> : <div className="settings-layout"><aside className="settings-nav"><a href="#providers">音声認識と翻訳</a><a href="#languages">言語と表示</a><a href="#remote">リモート接続</a><p>音声認識：Gladia<br />翻訳：DeepL<br />公開接続：ngrok</p></aside><div className="settings-main">
      {(!wizard || step === 1) && <section className="panel settings-section" id="providers"><span className="eyebrow">SERVICES</span><h2>音声認識と翻訳</h2><p>音声認識には相手の音声、翻訳には認識したテキストを送ります。</p><SecretField provider="gladia" label="音声認識 · Gladia" configured={settings.secrets.gladia?.configured || false} /><label className="field"><span>DeepL のプラン</span><select value={settings.deepl_mode} onChange={event => update('deepl_mode', event.target.value as 'free' | 'pro')}><option value="free">DeepL API Free</option><option value="pro">DeepL API Pro</option></select></label><button className="secondary" onClick={() => void action.run(save, 'プランと表示設定を保存しました。')}>プランを保存</button><SecretField provider="deepl" label="翻訳 · DeepL" configured={settings.secrets.deepl?.configured || false} /></section>}
      {(!wizard || step === 2) && <><section className="panel settings-section" id="languages"><span className="eyebrow">LANGUAGE & DISPLAY</span><h2>言語と表示</h2><div className="form-grid"><LanguageSelect label="相手が話す言語" value={settings.source_language} onChange={value => update('source_language', value)} languages={languages} /><LanguageSelect label="字幕の言語" value={settings.target_language} onChange={value => update('target_language', value)} languages={languages} /><label className="field"><span>テーマ</span><select value={settings.theme} onChange={event => update('theme', event.target.value)}><option value="system">OS の設定に合わせる</option><option value="light">ライト</option><option value="dark">ダーク</option></select></label><label className="field"><span>字幕サイズ · {settings.caption_font_size} px</span><input type="range" min="24" max="64" step="2" value={settings.caption_font_size} onChange={event => update('caption_font_size', Number(event.target.value))} /></label></div><label className="check-row"><input type="checkbox" checked={settings.show_original} onChange={event => update('show_original', event.target.checked)} />原文も表示する</label><label className="check-row"><input type="checkbox" checked={settings.translation_enabled} onChange={event => update('translation_enabled', event.target.checked)} />字幕を翻訳する</label><div className="privacy-line"><Icon name="headphones" /><span>PC 音声は字幕画面から明示的に共有します。通知音や他のアプリの音も共有対象に含まれます。</span></div></section>
      <section className="panel settings-section" id="remote"><span className="eyebrow">REMOTE CONNECTION</span><h2>リモート接続</h2><p>相手が別の PC から参加する場合、参加者用の HTTPS リンクを公開します。</p><SecretField provider="ngrok" label="公開接続 · ngrok" configured={settings.secrets.ngrok?.configured || false} /><label className="field"><span>ngrok の公開ドメイン</span><input type="text" value={settings.remote_domain} placeholder="your-domain.ngrok.app" onChange={event => update('remote_domain', event.target.value.trim())} maxLength={253} /></label><div className="button-row"><button disabled={action.busy} onClick={() => void action.run(async () => { await save(); const result = await api<{ url?: string; public_url?: string }>('/api/local/tunnel/start', 'POST', { request_id: requestId() }); const url = result.url || result.public_url; if (url) setPublicUrl(url); }, '公開接続の開始要求が完了しました。招待リンクは字幕画面で作成してください。')}>設定を保存して公開開始</button><button disabled={action.busy} onClick={() => void action.run(async () => { await api('/api/local/tunnel/stop', 'POST', { request_id: requestId() }); setPublicUrl(''); }, '公開接続を停止しました。')}>公開を停止</button></div>{publicUrl && <Notice>公開先：{publicUrl}</Notice>}</section></>}
      {wizard && step === 3 && <section className="panel settings-section"><span className="eyebrow">READY WHEN YOU ARE</span><h2>{finished ? '設定を保存しました' : '設定内容を確認'}</h2><p>相手の言語：{languageName(languages, settings.source_language)}<br />字幕の言語：{languageName(languages, settings.target_language)}</p><p>ホームの「通訳を開始」で準備が始まります。PC 音声の共有と相手のマイクは、それぞれ開始操作が必要です。</p><Link className="button primary" to="/">ホームへ進む <Icon name="arrow" /></Link></section>}
      {action.feedback}<div className="settings-actions">{wizard && step > 0 && <button onClick={() => setStep(step - 1)}>戻る</button>}<button className="primary" disabled={action.busy} onClick={() => void action.run(async () => { await save(); setFinished(true); if (wizard && step < 3) setStep(step + 1); }, '設定を保存しました。')}>{action.busy ? '保存中…' : wizard && step < 3 ? '保存して次へ' : '設定を保存'}</button></div>
    </div></div>}
  </>;
}

function DiagnosticsPage() {
  const [diagnostics, setDiagnostics] = useState<Record<string, unknown> | null>(null); const action = useAction(); const { snapshot, connection } = useSession(); const audio = useAudio();
  const refresh = async () => setDiagnostics(await api<Record<string, unknown>>('/api/local/diagnostics'));
  useEffect(() => { void refresh().catch(() => undefined); }, []);
  return <><div className="page-heading"><div><span className="eyebrow">CONNECTION HEALTH</span><h1>接続を、ひとつずつ確認。</h1><p>画面・音声・認識・翻訳の状態を分けて確認できます。</p></div><button disabled={action.busy} onClick={() => void action.run(refresh)}>診断を更新</button></div>{action.feedback}
    <div className="diagnostic-cards">{[['画面との接続', connection], ['音声認識', snapshot?.components.stt_status || 'idle'], ['翻訳サービス', snapshot?.components.translation_status || 'idle'], ['PC の音声共有', snapshot?.components.system_audio_status || 'idle']].map(([title, status]) => <section className="panel diagnostic-card" key={title}><span>{title}</span><Badge status={status} /></section>)}</div>
    <div className="settings-layout"><section className="panel settings-section diagnostic-help"><h2>うまく聞こえないときは</h2><ol><li>相手がマイクを開始し、入力レベルが動いているか確認してください。</li><li>原文だけが届く場合は翻訳サービスの設定を確認してください。</li><li>PC 音声は、字幕画面で共有を開始してください。</li><li>出力先や音量は OS の音声設定でも確認できます。</li></ol><Link className="button" to="/settings">サービスの設定へ</Link><button className="text-button" onClick={reconnect}>画面の接続をやり直す</button></section><section className="panel settings-section"><h2>診断データ</h2><p>サーバーが秘匿化した状態データです。会話本文と API キーを含めない形式で取得します。</p><dl className="metrics"><div><dt>ブラウザの入力サンプルレート</dt><dd>{audio.inputRate ? `${audio.inputRate} Hz` : '未測定'}</dd></div><div><dt>ブラウザの再生待ち</dt><dd>{Math.round(audio.queueMs)} ms</dd></div><div><dt>ブラウザ音声機能</dt><dd>{window.isSecureContext && navigator.mediaDevices ? '利用可能な環境' : 'HTTPS 接続が必要'}</dd></div></dl>{diagnostics ? <><pre className="diagnostic-json">{JSON.stringify(diagnostics, null, 2)}</pre><button onClick={() => { const blob = new Blob([JSON.stringify(diagnostics, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'translator-diagnostics.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}>診断データをダウンロード</button></> : <Notice>診断データはまだ取得できていません。「診断を更新」を押してください。</Notice>}</section></div>
    <div className="shutdown"><span>この PC の Translator を終了します。音声共有と公開接続も停止します。</span><button className="danger" disabled={action.busy} onClick={() => void action.run(async () => { await api('/api/local/shutdown', 'POST', { request_id: requestId() }); disconnect(); store.update({ connection: 'disconnected' }); }, 'アプリの終了を要求しました。この画面を閉じてください。')}>アプリを終了</button></div>
  </>;
}
