import { describe, expect, it } from 'vitest';
import { applyCaption, mergeCaption, settingsSchema } from './model';
import { caption, snapshot } from './test-fixtures';
describe('caption ordering and snapshot boundaries', () => {
  it('does not regress final original or translation with stale partial data', () => { const old = caption(); const next = caption(); next.original = { text: '你', revision: 1, is_final: false }; next.translation = { ...next.translation, text: 'こん', revision: 2, is_final: false }; expect(mergeCaption(old, next)).toEqual(old); });
  it('does not regress final to partial even at a larger revision', () => { const next = caption(); next.original = { text: '你', revision: 10, is_final: false }; next.translation.revision = 30; next.translation.is_final = false; expect(mergeCaption(caption(), next)).toEqual(caption()); });
  it('updates a previous utterance independently after the next one arrives', () => { let state = snapshot(); state = applyCaption(state, { session_id: 's', session_epoch: 1, event_seq: 5, data: caption('a') })!; state = applyCaption(state, { session_id: 's', session_epoch: 1, event_seq: 6, data: caption('b') })!; const next = caption('a'); next.translation.revision = 4; next.translation.text = '更新した翻訳'; state = applyCaption(state, { session_id: 's', session_epoch: 1, event_seq: 7, data: next })!; expect(state.captions.a.translation.text).toBe('更新した翻訳'); expect(state.captions.b.translation.text).toBe('こんにちは'); });
  it('ignores old session epochs, wrong sessions and snapshot duplicates', () => { const old = snapshot(); for (const event of [{ session_id: 's', session_epoch: 0, event_seq: 5 }, { session_id: 'other', session_epoch: 1, event_seq: 5 }, { session_id: 's', session_epoch: 1, event_seq: 4 }]) expect(applyCaption(old, { ...event, data: caption() })).toBe(old); });
  it('drops translations for old originals, languages, and translation generations', () => { for (const change of [{ based_on_original_revision: 1 }, { translation_epoch: 0 }]) { const next = caption(); next.translation = { ...next.translation, ...change, revision: 8, text: 'stale' }; expect(mergeCaption(caption(), next).translation.text).toBe('こんにちは'); } const next = caption(); next.target_language = 'en'; next.translation.revision = 8; next.translation.text = 'stale'; expect(mergeCaption(caption(), next).target_language).toBe('ja'); });
  it('allows translation disabled in a new generation and rejects later old results', () => { const disabled = caption(); disabled.translation = { ...disabled.translation, text: '', status: 'disabled', is_final: false, revision: 4, translation_epoch: 2 }; const merged = mergeCaption(caption(), disabled); expect(merged.translation.status).toBe('disabled'); const stale = caption(); stale.translation.revision = 20; expect(mergeCaption(merged, stale).translation.status).toBe('disabled'); });
  it('bounds memory to 100 utterances', () => { let state = snapshot(); for (let i = 0; i < 1000; i++) state = applyCaption(state, { session_id: 's', session_epoch: 1, event_seq: 5 + i, data: caption(String(i)) })!; expect(Object.keys(state.captions)).toHaveLength(100); expect(state.captions['999']).toBeDefined(); });
  it('accepts unset remote domain from real backend and uses empty form value', () => { expect(settingsSchema.parse({ remote_domain: null }).remote_domain).toBe(''); });
});
